// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRiY8PFOZUXHMHHk1Qz8dGADec3VEeEs',
    appId: '1:144904912696:web:ca3a13aed2e8dc59e94bcd',
    messagingSenderId: '144904912696',
    projectId: 'mindfit-72a7c',
    authDomain: 'mindfit-72a7c.firebaseapp.com',
    storageBucket: 'mindfit-72a7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpcxUdTWlImlSYeQgcBChxZAJM2fk33bU',
    appId: '1:144904912696:android:61ea2e0f28948305e94bcd',
    messagingSenderId: '144904912696',
    projectId: 'mindfit-72a7c',
    storageBucket: 'mindfit-72a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTr8A4X2OKAumEw3ARVn9RMTrsO0KKPTY',
    appId: '1:144904912696:ios:fa7656ac7ae3c5e6e94bcd',
    messagingSenderId: '144904912696',
    projectId: 'mindfit-72a7c',
    storageBucket: 'mindfit-72a7c.firebasestorage.app',
    iosBundleId: 'com.example.smartHasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTr8A4X2OKAumEw3ARVn9RMTrsO0KKPTY',
    appId: '1:144904912696:ios:fa7656ac7ae3c5e6e94bcd',
    messagingSenderId: '144904912696',
    projectId: 'mindfit-72a7c',
    storageBucket: 'mindfit-72a7c.firebasestorage.app',
    iosBundleId: 'com.example.smartHasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYRiY8PFOZUXHMHHk1Qz8dGADec3VEeEs',
    appId: '1:144904912696:web:f007983b2e75ec42e94bcd',
    messagingSenderId: '144904912696',
    projectId: 'mindfit-72a7c',
    authDomain: 'mindfit-72a7c.firebaseapp.com',
    storageBucket: 'mindfit-72a7c.firebasestorage.app',
  );
}
